version: 1
build:
  binary: millid
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: millicent-primary
  coins:
  - 4950000000000000uMILLI
- name: faucet
  coins:
  - 4950000000000000uMILLI
faucet:
  name: faucet
  coins:
  - 100uMILLI
  host: 0.0.0.0:4500
genesis:
  consensus_params:
    block:
      max_gas: "6000000"
  app_state:
    crisis:
      constant_fee:
        denom: uMILLI
    evm:
      params:
        evm_denom: uMILLI
    gov:
      deposit_params:
        min_deposit:
        - amount: "100000000"
          denom: uMILLI
    mint:
      minter:
        inflation: "0.000000000000000000"   
        annual_provisions: "0.000000000000000000"
      params:
        mint_denom: uMILLI
        inflation_max: "0.000000000000000000"
        inflation_min: "0.000000000000000000"
        goal_bonded: "1.000000000000000000"
        blocks_per_year: "15778800"
    staking:
      params:
        bond_denom: uMILLI
    slashing:
      params:
        downtime_jail_duration: "86400s"
    crisis:
      constant_fee:
        denom: uMILLI
        amount: "1000"
    wasm:
      params:
        instantiate_default_permission: Nobody
  chain_id: millicent-testnet
